### ISSUE TITLE
Need for a way to enable cooperative editing

### ISSUE THREAD

**Issue by lehors** [lfai/model_openness_tool#10]
The MOT should support a crowdsourcing type of interaction similar to what a wiki provides to enable additions and editing of its data.

Implementing this kind of capability with the right access control is however no small task. One alternative might be to leverage GitHub to manage the data and feed the MOT with that data instead. The MOT UI would then be primarily read only and we'd leverage the standard GitHub PR workflow to provide for control over the changes to the data. GitHub actions could be used to feed updates to the MOT.

The "Opening up ChatGPT" project does something like that using YAML files for input: https://github.com/opening-up-chatgpt/opening-up-chatgpt.github.io/?tab=readme-ov-file#how-to-contribute

**Comment by gregcube** [comment]
> leverage GitHub to manage the data and feed the MOT with that data instead. The MOT UI would then be primarily read only and we'd leverage the standard GitHub PR workflow to provide for control over the changes to the data. GitHub actions could be used to feed updates to the MOT.

Going this route.  I have it working in my forked repo using github workflows/ actions; however, after more thought, would it be wise to have models in their own, standalone repository, rather than packaged in with the website code?  I could see a few benefits in doing this.  Let me know your thoughts.

**Comment by lehors** [comment]
I thought about this too but I see this mostly as an implementation detail. :-)
At this point I'd be happy to just add a new sub directory for the models, plus possibly move all the tool stuff into its own sub directory, but I don't really feel strongly about it so happy to hear why you think that'd be worthwhile.

**Comment by lehors** [comment]
Addressed by PR #21
