### ISSUE TITLE
Update Drupal core to 10.3.10

### ISSUE THREAD

**Issue by gregcube** [lfai/model_openness_tool#58]
Upgrade Drupal core to the latest version on the 10.3.x branch, which is 10.3.10 as of this issue's creation.

**Comment by lehors** [comment]
I noticed that too and just put together a PR to address that as a matter of fact. See PR #59.

**Comment by lehors** [comment]
Addressed by PR #59.

**Comment by lehors** [comment]
Actually, this may not be all because I don't think the deploy action acts on the changes to composer.json/lock, right?
My account doesn't give me access to the drupal config dashboard so I can't even inspect to find out.

**Comment by gregcube** [comment]
> Actually, this may not be all because I don't think the deploy action acts on the changes to composer.json/lock, right?

The deploy action does handle composer updates/changes. Stage and production sites are 10.3.10 now. So it worked. Good stuff!

> My account doesn't give me access to the drupal config dashboard so I can't even inspect to find out.

What account do you log in with?  I'll make sure you're an administrator.

**Comment by lehors** [comment]
> > Actually, this may not be all because I don't think the deploy action acts on the changes to composer.json/lock, right?
> 
> The deploy action does handle composer updates/changes. Stage and production sites are 10.3.10 now. So it worked. Good stuff!

Indeed! Well done. :-)

> 
> > My account doesn't give me access to the drupal config dashboard so I can't even inspect to find out.
> 
> What account do you log in with? I'll make sure you're an administrator.

arnaud.lehors@local.ai

Please, create that account on the staging server also.
Thanks.
